site_name: Taller de X

nav:
  - Introducción: 'index.md'
  - Instalación:
    - Windows: 'instalacion/windows.md'
    - Mac OS: 'instalacion/macos.md'
    - Linux: 'instalacion/linux.md'
  
markdown_extensions:
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'red'
  font:
    text: 'Roboto Mono'
    code: 'Roboto Mono'
  icon: 'images/logo.png'
  favicon: 'images/favicon.png'
  language: 'es'
  
  repo_name: 'LaJaqueria/plantilla-taller'
  repo_url: 'https://github.com/LaJaqueria/plantilla-taller'
  extra:
    social:
      - type: 'github'
        link: 'https://github.com/LaJaqueria'
      - type: 'twitter'
        link: 'https://twitter.com/lajaqueria'
      - type: 'linkedin'
        link: 'https://www.linkedin.com/company/lajaqueria/'

